title: "Cvio - CV Resume & Personal Portfolio Jekyll Theme"
email: "your-email@example.com"
description: "Jekyll Resume / CV / vCard / Portfolio / Personal template"
author: "Admin"
baseurl: /newcv # the subpath of your site, e.g. /blog
url: https://ahmedsharifkhan.github.io # the base hostname & protocol for your site, e.g. http://example.com
date_format: "%d %B %Y"

# paginations & permalinks
paginate: 9
paginate_path: "/blog/page:num/"
permalink: pretty

# disqus comments
disqus_comments: "yes" # yes - show disqus comments, no - hide disqus comments
disqus_shortname: "glitche-jekyll-theme" # read more here https://help.disqus.com/customer/portal/articles/466208-what-s-a-shortname-

# formsubmit.io
formsubmit_email: "beshleyweb@gmail.com" # sign up on https://formsubmit.io/ and confirm your email

# collections
collections:
  - works

# archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# Build settings
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

sass:
  style: compressed

markdown:  kramdown